### ISSUE TITLE
Formatting not working in 0.4

### ISSUE THREAD

**Issue by bemyak** [karuna/tera-vscode#7]
Extension is failing to register the formatter due to the error:
```
[11140:1121/001103.075475:INFO:CONSOLE(5407)] "Activating extension 'karunamurti.tera' failed: Cannot find module 'prettydiff'
Require stack:
- ~/.vscode/extensions/karunamurti.tera-0.0.4/lib/format.js
- ~/.vscode/extensions/karunamurti.tera-0.0.4/lib/index.js
- /opt/visual-studio-code/resources/app/out/vs/loader.js
- /opt/visual-studio-code/resources/app/out/bootstrap-amd.js
- /opt/visual-studio-code/resources/app/out/bootstrap-fork.js.", source: file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js (5407)
```

I believe this is caused by this change: https://github.com/karuna/tera-vscode/commit/896d1956c798da0bc274bb6ae07c22ec583fcb21#diff-0a721cd4753ff50bbbe1237397c3c7692080254fa766268fcc8b05ef633c50bfR6

Since we're not adding `node_modules` to the build anymore, `prettyformatter` can't be imported.

**Comment by karuna** [comment]
@bemyak I've added node_modules back

**Comment by bemyak** [comment]
@karuna , thanks, works now!
